apiVersion: apps/v1
kind: Deployment
metadata: 
  name: auth-depl
spec:
  replicas: 1
  selector: 
    matchlabels: 
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec: 
      containers:
        - name: auth
        image: ruanritah/ticketing-auth

---

apiVersion: v1
kind: service
metadata: 
  name: auth-srv
spec: 
  selector:
    app: auth
  ports: 
    - name: auth
    protocol: TCP
    port: 3000
    targetPort: 3000